### PR TITLE
Added files for Gemma

### PR DESCRIPTION
**Pull request by MiguelCidadeSilva**

### CODE REVIEW

**Comment by JoseBambora** [comment]
You should add the documentation to your final notebook and not on README.md.

**Comment by MiguelCidadeSilva** [comment]
I don't have a final notebook, i have basically three copies of notebooks that run zero shot learning, then I have a second notebook that has code for one shot and few shot, but that code does not work properly, therefore I didn't go much in depth as it would be repeated, so I used markdown for the common things. If you want I can change, but since this part has a somewhat different structure, also if you notice while things aren't too complex I added comments on all notebooks.

**Comment by AbhimanyuAryan** [comment]
> I don't have a final notebook, i have basically three copies of notebooks that run zero shot learning, then I have a second notebook that has code for one shot and few shot, but that code does not work properly, therefore I didn't go much in depth as it would be repeated, so I used markdown for the common things. If you want I can change, but since this part has a somewhat different structure, also if you notice while things aren't too complex I added comments on all notebooks.

add it on main readme.md and explain more about gemma architecture and things in same format I did for distilbert

**Comment by MiguelCidadeSilva** [comment]
Ok, I guess I can do that, I'll keep you guys updated, hopefully later today it gets done.

**Pull request merged**
